In [2]:
def second_largest(nums):
    largest = None
    second = None
    for num in nums:
        if largest is None or num>largest:
            second = largest
            largest = num
        if num!=largest and (second is None or num>second):
            second = num
            
    return second

print(second_largest([1,2,3,4,5]))
print(second_largest([5,5,5]))
print(second_largest([10]))

4
None
None

In [ ]:
def add_item(item, basket=None):
    if basket is None:
        basket = []
    basket.append(item)
    return basket

In [3]:
def check_anagrams(a,b):
    return "".join(sorted(a)) == "".join(sorted(b))

print(check_anagrams('listen', 'silent'))
print(check_anagrams('hello', 'world'))

True
False

In [4]:
def flatten(lstt):
    result = []
    for item in lstt:
        if isinstance(item,list):
            result.extend(flatten(item))
        else:
            result.append(item)
            
    return result

print(flatten([1, [2, 3], [4, [5, 6]], 7]))

[1, 2, 3, 4, 5, 6, 7]

In [5]:
def find_pairs(nums, target):
    # num_set = set(nums)
    seen = set()
    result = []
    for num in nums:
        complement = target - num
        if complement in seen:
            result.append((complement, num))
        seen.add(num)
        
    return result
print(find_pairs([2,7,11,15], 9))

[(2, 7)]

In [6]:
def describe(*args, **kwargs):
    print(args)
    print(kwargs)

describe(1, 2, 3, name="claude", role="assistant")

(1, 2, 3)
{'name': 'claude', 'role': 'assistant'}

In [8]:
def is_rotation(a,b):
    if len(a) != len(b):
        return False
    return b in (a+a)

print(is_rotation('waterbottle', 'erbottlewat'))

True

In [9]:
def count_vowels(s):
    count = 0
    for ch in s:
        if ch.lower() in {'a', 'e', 'i', 'o', 'u'}:
            count+=1
    return count

print(count_vowels('Hello'))

2

In [10]:
def group_anagrams(words):
    
    groups = {}
    for word in words:
        key = "".join(sorted(word))
        if key not in groups:
            groups[key] = []
        groups[key].append(word)
        
    return list(groups.values())

print(group_anagrams(["eat", "tea", "tan", "ate", "nat", "bat"]))

[['eat', 'tea', 'ate'], ['tan', 'nat'], ['bat']]

In [12]:
def valid_parenthesis(s):
    stack = []
    pairs = {
        "}": '{',
        ')': "(",
        ']' : "["
    }
    for ch in s:
        if ch in "{[(":
            stack.append(ch)
        elif ch in "}])":
            if not stack:
                return False
            top = stack.pop()
            if top != pairs[ch]:
                return False
    return len(stack) == 0

print(valid_parenthesis('{[()]}'))
print(valid_parenthesis('{[()]'))

True
False

In [13]:
def is_palindrome(s):
    cleaned_s = "".join([x.lower() for x in s if x.isalnum()])
    return cleaned_s == cleaned_s[::-1]

print(is_palindrome("A man, a plan, a canal: Panama"))
print(is_palindrome("hello"))

True
False

In [19]:
def missing_num(nums):
    n = len(nums)+1
    
    expected = n * (n+1)//2
    return expected-sum(nums)

print(missing_num([1,2,3,5]))

4

In [21]:
def pair_difference(nums, target):
    num_set = set(nums)
    seen = set()
    result = []
    for num in nums:
        complement = target + num
        if complement in num_set:
            pairs = (complement, num)
            if pairs not in seen:
                result.append(pairs)
                seen.add(pairs)
        
    return result

print(pair_difference([1,5,3,4,2], 2))

[(3, 1), (5, 3), (4, 2)]

In [30]:
from functools import wraps

def memorize(func):
    
    cache = {}
    
    @wraps(func)
    def wrapper(*args, **kwargs):
        key = (args, tuple(sorted(kwargs.items())))
        if key not in cache:
            cache[key] = func(*args, **kwargs)
        return cache[key]
    wrapper.cache = cache
    return wrapper

@memorize
def fibonocci(n):
    if n < 2:
        return n
    return fibonocci(n-1) + fibonocci(n-2)

import time

start = time.perf_counter()
print(fibonocci(30))
end = time.time()
print(f"Execution time: {time.perf_counter() - start:.6f} seconds")

832040
Execution time: 0.000501 seconds

In [31]:
start = time.perf_counter()
print(fibonocci(30))
end = time.time()
print(f"Execution time: {time.perf_counter() - start:.6f} seconds")

832040
Execution time: 0.000411 seconds

In [32]:
print("cache size:", len(fibonocci.cache))

cache size: 31

In [36]:
def fib(n):
    a, b = 0, 1
    for _ in range(n):
        print(a, end=" ")
        a, b = b, a+b

fib(10)

0 1 1 2 3 5 8 13 21 34

In [39]:
def first_repeating(s):
    
    counter = {}
    for ch in s:
        counter[ch] = counter.get(ch, 0) + 1
    for ch in s:
        if counter[ch] == 1:
            return ch
    return None
print(first_repeating('leetcode'))
print(first_repeating('swiss'))
print(first_repeating('dawn'))

l
w
d

In [40]:
def flatten_matrix(mat):
    result = []
    for i in mat:
        for j in i:
            result.append(j)
    return result

flatten_matrix([[1, 2, 3], [4, 5, 6]])

[1, 2, 3, 4, 5, 6]

In [43]:
def rotate_array(nums, k):
    if not nums:
        return nums
    k = k % len(nums)
    return nums[-k:] + nums[:-k]

print(rotate_array([1,2,3,4,5], 2))
print(rotate_array([1,2,3], 4))

[4, 5, 1, 2, 3]
[3, 1, 2]

In [47]:
def longest_unique_substring(s):
    longest = 0
    l = 0
    seen = set()
    for r in range(len(s)):
        while s[r] in seen:
            seen.remove(s[l])
            l+=1
        w = (r-l) + 1
        longest = max(longest, w)
        seen.add(s[r])
    return longest

print(longest_unique_substring("abcabcbb"))    # 3  ("abc")
print(longest_unique_substring("bbbbb"))       # 1  ("b")
print(longest_unique_substring("pwwkew"))      # 3  ("wke")
print(longest_unique_substring(""))            # 0
print(longest_unique_substring("abcdab"))      # 4  ("cdab")

3
1
3
0
4

In [1]:
import pandas as pd

df = pd.DataFrame({
    'id':[1,2,3],
    'name':['ajai', 'ajith', 'joel'],
    'age': [27, 30, 24],
    'job': ['AI', "Design", "Design"]})

df

   id   name  age     job
0   1   ajai   27      AI
1   2  ajith   30  Design
2   3   joel   24  Design

In [6]:
df.loc[0:2]

   id   name  age     job
0   1   ajai   27      AI
1   2  ajith   30  Design
2   3   joel   24  Design

In [14]:
import numpy as np

def rolling_average(arr, window=3):
    
    averages = []
    for i in range(len(arr)-window+1):
        window_list = arr[i:i+window]
        averages.append(np.average(window_list))
    return(np.array(averages)) 
    

sales = np.array([120, 85, 90, 200, 150, 60, 175])
print(rolling_average(sales, 3))
# expected: [ 98.33333333 125.         146.66666667 136.66666667 128.33333333]

[ 98.33333333 125.         146.66666667 136.66666667 128.33333333]

In [15]:
import pandas as pd

df = pd.DataFrame({
    "user_id": ["a", "b", "a", "c", "b", "a", "d"],
    "amount":  [10,  20,  5,  50,  30,  15,  8]
})

# your code here
df

  user_id  amount
0       a      10
1       b      20
2       a       5
3       c      50
4       b      30
5       a      15
6       d       8

In [18]:
df.sort_values('amount',ascending=False).head(3)

  user_id  amount
3       c      50
4       b      30
1       b      20

In [20]:
df.groupby('user_id')['amount'].sum().sort_values(ascending=False).head(3)

user_id
b    50
c    50
a    30
Name: amount, dtype: int64

In [23]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 4, 4],
    [10, 0, 0]
])

# your code here — expected:
# [[0.16666667 0.33333333 0.5       ]
#  [0.33333333 0.33333333 0.33333333]
#  [1.         0.         0.        ]]

result = arr / arr.sum(axis=1, keepdims=True)
result

array([[0.16666667, 0.33333333, 0.5       ],
       [0.33333333, 0.33333333, 0.33333333],
       [1.        , 0.        , 0.        ]])

In [24]:
arr.sum(axis=1, keepdims=True)

array([[ 6],
       [12],
       [10]])

In [34]:
df = pd.DataFrame({
    'date': ['2026-01-15', '2025-12-20']
})
df

         date
0  2026-01-15
1  2025-12-20

In [35]:
df['date'] = pd.to_datetime(df['date'])
df['month'] = df['date'].dt.month
df

        date  month
0 2026-01-15      1
1 2025-12-20     12

In [39]:
arr = np.array([1.0, 2.0, np.nan, 4.0, np.nan, 6.0])
[i for i in arr if i!=np.nan]

[1.0, 2.0, nan, 4.0, nan, 6.0]

In [40]:
import numpy as np

arr = np.array([1.0, 2.0, np.nan, 4.0, np.nan, 6.0])

mean = np.nanmean(arr)
mask = np.isnan(arr)

print(mean)
print(mask)

3.25
[False False  True False  True False]

In [41]:
import pandas as pd

orders = pd.DataFrame({
    "order_id": [1, 2, 3, 4],
    "user_id":  ["a", "b", "c", "z"]    # "z" has no matching user
})

users = pd.DataFrame({
    "user_id": ["a", "b", "c"],
    "signup_date": ["2025-01-01", "2025-02-15", "2025-03-10"]
})

# your code here

In [42]:
orders

   order_id user_id
0         1       a
1         2       b
2         3       c
3         4       z

In [43]:
users

  user_id signup_date
0       a  2025-01-01
1       b  2025-02-15
2       c  2025-03-10

In [44]:
pd.merge(orders, users, on='user_id', how='left')

   order_id user_id signup_date
0         1       a  2025-01-01
1         2       b  2025-02-15
2         3       c  2025-03-10
3         4       z         NaN

In [49]:
arr = np.array([5, 1, 9, 3, 7, 2, 8])
# find indices of the 3 largest values, without a full sort
np.argpartition(arr,-3)[-3:]

array([4, 6, 2], dtype=int64)

In [53]:
import pandas as pd

orders = pd.DataFrame({
    "order_id": [1, 2, 3, 4, 5],
    "status": ["completed", "cancelled", "pending", "completed", "completed"]
})

# your code here
orders['is_completed'] = orders['status'].apply(lambda x: True if x=='completed' else False)
orders

   order_id     status  is_completed
0         1  completed          True
1         2  cancelled         False
2         3    pending         False
3         4  completed          True
4         5  completed          True

In [2]:
import pandas as pd
employees = pd.DataFrame({
    "name":       ["Alice", "Bob", "Carol", "Dave", "Eve"],
    "department": ["eng", "eng", "sales", "sales", "eng"],
    "salary":     [100, 150, 80, 120, 50]
})

# employees['salary_pct_of_dept'] = 
employees

    name department  salary
0  Alice        eng     100
1    Bob        eng     150
2  Carol      sales      80
3   Dave      sales     120
4    Eve        eng      50

In [ ]:
employees['salary_pct_of_dept'] = employees['salary'] / employees.groupby('department')['salary'].transform('sum') *100
employees

    name department  salary  salary_pct_of_dept
0  Alice        eng     100                  33
1    Bob        eng     150                  50
2  Carol      sales      80                  40
3   Dave      sales     120                  60
4    Eve        eng      50                  16